# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "525f24980473e535a3a43889943037f9"
application_url = "https://7776-106-219-159-62.ngrok-free.app"
embedded = true
name = "shipment-test"
handle = "shipment-test-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bubble-bazaar-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "products/create", "products/update" ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_collection_listings,read_customers,read_fulfillments,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_product_listings,read_products,read_shipping,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_customers,write_fulfillments,write_inventory,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_shipping,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://7776-106-219-159-62.ngrok-free.app/auth/callback",
  "https://7776-106-219-159-62.ngrok-free.app/auth/shopify/callback",
  "https://7776-106-219-159-62.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
